app/models/hotsauce.py
from app.extensions import db
from app.models.user import User


class HotSauce(db.Model):
    """HotSauce."""
    __tablename__ = "hot_sauces"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    base = db.Column(db.String(20), nullable=False)
    pepper = db.Column(db.String(20), nullable=False)
    bottle = db.Column(db.String(20), nullable=False)


class Rating(db.Model):
    """User's rating of a hot sauce."""
    __tablename__ = "ratings"
    hotsauce_id = db.Column(db.Integer, db.ForeignKey('hot_sauces.id'), primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    flavor = db.Column(db.Integer, nullable=False)
    heat = db.Column(db.Integer, nullable=False)

app/hotsauces/__init__.py
from flask import Blueprint

bp = Blueprint('hotsauces', __name__)


from app.hotsauces import routes

app/hotsauces/routes.py
from app.hotsauces import bp
from app.extensions import db
from app.models.hotsauce import HotSauce, Rating
from app.forms import HotSauceForm, RateHotSauceForm
from flask import render_template, redirect, url_for, flash, session, abort


def format_bottle_style(bottle_style):
    # Replace spaces with hyphens and append '.png'
    return '-'.join(bottle_style.split()).lower() + '.png'

@bp.route("/")
def show_all_hot_sauces():
    """Return a list of hot sauces."""

    all_hotsauces = HotSauce.query.all()
    # Calculate average ratings for each hot sauce
    average_ratings = {}
    for hot_sauce in all_hotsauces:
        ratings = Rating.query.filter_by(hotsauce_id=hot_sauce.id).all()
        if ratings:
            total_flavor = sum(rating.flavor for rating in ratings)
            total_heat = sum(rating.heat for rating in ratings)
            average_flavor = total_flavor / len(ratings)
            average_heat = total_heat / len(ratings)
            average_ratings[hot_sauce.id] = {
                'image_filename': format_bottle_style(hot_sauce.bottle),
                'flavor': average_flavor,
                'heat': average_heat
            }
        else:
            average_ratings[hot_sauce.id] = {
                'image_filename': format_bottle_style(hot_sauce.bottle),
                'flavor': 5,
                'heat': 5
            }

    return render_template('hotsauces/all_hotsauces.html', title='Hot Sauces', hotsauces=all_hotsauces,
                           average_ratings=average_ratings)


@bp.route("/add", methods=['GET', 'POST'])
def add_hot_sauce():
    form = HotSauceForm()
    if form.validate_on_submit():
        hot_sauce = HotSauce(
            name=form.name.data,
            base=form.base.data,
            pepper=form.pepper.data,
            bottle=form.bottle.data
        )
        db.session.add(hot_sauce)
        db.session.commit()
        flash('Hot sauce added successfully!', 'success')
        return redirect(url_for('hotsauces.show_all_hot_sauces'))  # Redirect to the list of hot sauces
    return render_template("hotsauces/new_hotsauce.html", title='Add Hot Sauce', form=form)


@bp.route("/rate", methods=["GET", "POST"])
def rate_hotsauce():
    """Rate a Hot Sauce."""
    form = RateHotSauceForm()

    # Retrieve hot sauces not already rated by the user
    rated_hotsauces = Rating.query.filter_by(user_id=session.get("user_id")).all()
    unrated_hotsauces = HotSauce.query.filter(HotSauce.id.notin_([rating.hotsauce_id for rating in rated_hotsauces])).all()
    form.hotsauce.choices = [(hotsauce.id, hotsauce.name) for hotsauce in unrated_hotsauces]

    if form.validate_on_submit():
        hotsauce_id = form.hotsauce.data
        flavor = form.flavor.data
        heat = form.heat.data

        # Check if the user has already rated this hot sauce
        existing_rating = Rating.query.filter_by(user_id=session.get("user_id"), hotsauce_id=hotsauce_id).first()
        if existing_rating:
            flash('You have already rated this hot sauce.', 'warning')
            return redirect(url_for('rate_hotsauce'))

        new_rating = Rating(hotsauce_id=hotsauce_id, user_id=session.get("user_id"), flavor=flavor, heat=heat)
        db.session.add(new_rating)
        db.session.commit()
        flash('Hot sauce rated successfully!', 'success')
        return redirect(url_for('main.index'))

    return render_template("hotsauces/rate_hotsauce.html", form=form)


@bp.route("/<int:hotsauce_id>")
def hotsauce_details(hotsauce_id):
    # Retrieve the hot sauce from the database
    hot_sauce = HotSauce.query.get(hotsauce_id)

    if hot_sauce:
        # Render a template to display the hot sauce details
        image =  {
            'filename': format_bottle_style(hot_sauce.bottle)
            }
        return render_template('hotsauces/hotsauce.html', title='Hot Sauce Details', hotsauce=hot_sauce, image=image)
    else:
        # If the hot sauce does not exist, return a 404 error
        abort(404)

app/templates/hotsauces/all_hotsauces.html
{% extends 'base.html' %}

{% block content %}

<h1>Check out the Hot Sauces!</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Average Flavor Rating</th>
      <th>Average Heat Rating</th>
    </tr>
  </thead>
  <tbody>
    {% for hotsauce in hotsauces %}
      {% set image_name = average_ratings[hotsauce.id]['image_filename'] %}
      <tr>
        <td><img src="{{ url_for('static', filename='images/' + image_name) }}" width="60" height="60" alt="{{ hotsauce['name'] }}"></td>
        <td><a href="{{ url_for('hotsauces.hotsauce_details', hotsauce_id=hotsauce.id) }}">{{ hotsauce.name }}</a></td>
        <td>{{ average_ratings[hotsauce.id]['flavor'] }} / 10</td>
        <td>{{ average_ratings[hotsauce.id]['heat'] }} / 10</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<p><a class="btn btn-primary" href="{{ url_for('hotsauces.add_hot_sauce') }}">Add a new Hot Sauce</a></p>

{% endblock %}

app/templates/hotsauces/hotsauce.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
  <h2>Hot Sauce Details</h2>
  <h3>Name: {{ hotsauce.name }}</h3>
  <img src="{{ '/static/images/' +  image['filename'] }}" width="200" height="200" alt="{{ hotsauce.name }} bottle">
  <p><strong>Base:</strong> {{ hotsauce.base }}</p>
  <p><strong>Pepper:</strong> {{ hotsauce.pepper }}</p>
  <p><strong>Bottle Type:</strong> {{ hotsauce.bottle }}</p>
</div>

{% endblock %}

app/templates/hotsauces/new_hotsauce.html
{% extends 'base.html' %}

{% block content %}

<h1>Add a new hot sauce to the database!</h1>
<form method="POST">
  {% include "_form.html" %}
  <button class="btn btn-primary" type="submit">Add</button>
</form>

{% endblock %}

app/templates/hotsauces/rate_hotsauce.html
{% extends 'base.html' %}

{% block content %}

<h1>Rate a Hot Sauce</h1>

<form method="POST">
  {% include "_form.html" %}
  <button class="btn btn-primary" type="submit">Rate</button>
</form>


{% endblock %}